### ISSUE TITLE
Warden Givefreeday: Missing translation / FF issue with teamgames

### ISSUE THREAD

**Issue by mrkos9i4ok** [shanapu/MyJailbreak#148]
1)
```
L 11/23/2016 - 19:10:42: [SM] Exception reported: Language phrase "request_givefreeday" not found
L 11/23/2016 - 19:10:42: [SM] Blaming: MyJailbreak/warden.smx
L 11/23/2016 - 19:10:42: [SM] Call stack trace:
L 11/23/2016 - 19:10:42: [SM]   [0] Format
L 11/23/2016 - 19:10:42: [SM]   [1] Line 101, MyJailbreak/Modules/Warden/freedays.sp::Command_FreeDay
L 11/23/2016 - 19:10:42: [SM]   [3] FakeClientCommand
L 11/23/2016 - 19:10:42: [SM]   [4] Line 985, MyJailbreak/menu.sp::JBMenuHandler
```

2)When use KissLicks TeamGames don`t work FF in menu and FF in games(last version 1.1.0.7(

**Comment by shanapu** [comment]
How often do I have to tell you: 

- Read all issues [...] if your request was already posted there.
- **Use descriptive topic titles & descriptions.**
- **Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!**
- **Try to explain your request with so many details as you can.**
- **Because of the Language gap (also on my side) it's very hard to understand everything.**
- Expound every single step to reproduce your train of thought. **We're all no clairvoyant or mindreaders.** 
- Explain like "I'm an idiot and never I played MyJailbreak before". 
- Otherwise I'm going to ignore you.

1) seems I forgot to push the version with latest changes. I will fix this in ~4hours when im back home. 

2) Like i already said in the other issue - the FF in menu is still todo. 
Please show me your TG config.
In which games FF don't work?
Is FF in these games don't working for both teams or only one team? which team?

**Comment by shanapu** [comment]
`L 11/23/2016 - 19:10:42: [SM] Exception reported: Language phrase "request_givefreeday" not found`
`L 11/23/2016 - 19:10:42: [SM] Blaming: MyJailbreak/warden.smx`
`L 11/23/2016 - 19:10:42: [SM] Call stack trace:`
`L 11/23/2016 - 19:10:42: [SM]   [0] Format`
`L 11/23/2016 - 19:10:42: [SM]   [1] Line 101, MyJailbreak/Modules/Warden`/freedays.sp::Command_FreeDay
`L 11/23/2016 - 19:10:42: [SM]   [3] FakeClientCommand`
`L 11/23/2016 - 19:10:42: [SM]   [4] Line 985, MyJailbreak/menu.sp::JBMenuHandler`

I just see **Line 101** error is **Language phrase "request_givefreeday" not found`** but when i check the latest file -> https://github.com/shanapu/MyJailbreak/blob/dev/addons/sourcemod/scripting/MyJailbreak/Modules/Warden/freedays.sp#L102 there is no "request_givefreeday" there is a **"warden_givefreeday"**

So i don't have forget to push the latest - you forgot to update to latest. 
maybe the binary (.smx) files are outdated. I always recommend to compile dev brach foryourself.

Solution: update to latest dev!

**Comment by mrkos9i4ok** [comment]
The problem was solved with the games, but there is a new Zeus.

Zeus just takes and kills prisoners. (1 cartridge)
(Although I must work as handcuffs)

**Comment by shanapu** [comment]
> Otherwise I'm going to ignore you.
