### ISSUE TITLE
Suggestions; simple ball, PlayersVote, a few bugs

### ISSUE THREAD

**Issue by Include5** [shanapu/MyJailbreak#157]
##  This plugins let's you spawn a simple ball on your servers. The ball can be kicked by pressing the use (E) button. When the ball holder is attacked, he will drop the ball.
**Maybe you add this to the warden?**

[https://forums.alliedmods.net/showthread.php?p=2423345](url)

## When players kick warden he can again become a warden. Maybe limit this possibility for kicked guards to the next round?

**Players vote for kick warden >> Warden kicked >>> Guard become warden again**

![111](https://cloud.githubusercontent.com/assets/20662946/21647293/b35072a6-d2aa-11e6-8b75-e2fe02da18db.png)
**Best T: console. Inflicted damage: 0 hp and etc..**

![11111](https://cloud.githubusercontent.com/assets/20662946/21647373/1394b35c-d2ab-11e6-9667-53041d1982db.png)
**Mr.Frog  was revived due frekill
debug warden is... what's this?**

# Beta 9.1.dev-fd40083
# [01] SourceMod (1.8.0.5967) by AlliedModders LLC

**Comment by shanapu** [comment]
dude 😞, not the first time: 
## [Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum)

I will close this and open two new issues for Ball plugin & the deal damage bug.

The `debug warden is...` is a debug message i forget to removed. fixed with upcoming commit.
Thanks for report!
