### ISSUE TITLE
 several proposals

### ISSUE THREAD

**Issue by dolmat58** [shanapu/MyJailbreak#186]
1 - And yet necessary function is to ask the new players CT that would test their knowledge of the rules of jail.
2 - Add to the commander of the menu to enable and disable bhop for him and the players.
3 - The mini game of hide and seek to make the ability to hide in objects.
4 - Ability to change the gravity, the speed of life and commander

**Comment by shanapu** [comment]
What should I consider if I open a issue or post on forum?

- Use descriptive topic titles & descriptions. i have idea, need Help, Suggestion or don't work isn't helpful & pleasant.
- Try to explain your request with so many details as you can.
- USE PROPER ENGLISH!
- Expound every single step to reproduce your train of thought. We're all no clairvoyant or mindreaders.
- Explain like "I'm an idiot and never I played MyJailbreak before".
- Maybe take a screenshot or make a beautiful picture with paint.

**- Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!**

**Comment by shanapu** [comment]
Please before open an Issue take a look to [FAQ](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions)s - [What should I consider if I open a issue or post on forum?](https://github.com/shanapu/MyJailbreak/wiki/Frequently-Asked-Questions#what-should-i-consider-if-i-open-a-issue-or-post-on-forum)

-> _Please open one Issue on github per request/errors/problems. Split many requests/errors/problems to different Issues. Thanks!_

> 2 - Add to the commander of the menu to enable and disable bhop for him and the players.
> 4 - Ability to change the gravity, the speed of life and commander

this was asked before and i don't think I will include these advantages to MyJailbreak. These are to overpowered & will unbalance the game.

3 - The mini game of hide and seek to make the ability to hide in objects.

I don't want to copy the Hide & Seek scheme. That's why Its called "Hide in the dark". I also don't wanna make whistles in the game. Would be to simliar and need more time to play, what could be annoning for dead players.
Also to put csgo props on a jailmap is nearly stupid,  there are normaly no standart props on jail maps... 
would look weired when a barrel is standing on jb_clouds. 

> 1 - And yet necessary function is to ask the new players CT that would test their knowledge of the rules of jail.

Sry, I don't understand.
